from ocelot.cpbd.elements import (
    Solenoid,
    # SBend,
    RBend,
    Bend,
    Quadrupole,
    Sextupole,
    Octupole,
    Monitor,
    Marker,
    Cavity,
    Hcor,
    Vcor,
    Undulator,
    Matrix,
    TDCavity,
    Aperture,
    Drift,
    Hcor,
)
from ocelot.cpbd.elements.cor_atom import CorAtom

ocelot_conversion_rules = {
    "dipole": RBend,
    "solenoid": Solenoid,
    "quadrupole": Quadrupole,
    "sextupole": Sextupole,
    "octupole": Octupole,
    "beam_position_monitor": Marker,
    "beam_arrival_monitor": Drift,
    "bunch_length_monitor": Drift,
    "screen": Marker,
    "rcollimator": Aperture,
    "collimator": Aperture,
    "monitor": Monitor,
    "wall_current_monitor": Drift,
    "integrated_current_transformer": Drift,
    "faraday_cup": Drift,
    "cavity": Cavity,
    "rf_deflecting_cavity": TDCavity,
    "aperture": Aperture,
    "shutter": Drift,
    "valve": Drift,
    "bellows": Drift,
    "cleaner": Drift,
    "lscdrift": Drift,
    "csrdrift": Drift,
    "kicker": Hcor,
    "longitudinal_wakefield": Drift,
}
