from ocelot.cpbd.elements import (
  Solenoid,
  # SBend,
  # RBend,
  Bend,
  Quadrupole,
  Sextupole,
  Octupole,
  Monitor,
  Marker,
  Cavity,
  Hcor,
  Vcor,
  Undulator,
  Matrix,
  TDCavity,
  Aperture,
  Drift,
)

ocelot_conversion_rules = {
  "dipole": Bend,
  "solenoid": Solenoid,
  "quadrupole": Quadrupole,
  "sextupole": Sextupole,
  "octupole": Octupole,
  "beam_position_monitor": Marker,
  "beam_arrival_monitor": Monitor,
  "bunch_length_monitor": Monitor,
  "screen": Marker,
  "rcollimator": Aperture,
  "collimator": Aperture,
  "monitor": Monitor,
  "wall_current_monitor": Monitor,
  "integrated_current_transformer": Monitor,
  "faraday_cup": Monitor,
  "cavity": Cavity,
  "rf_deflecting_cavity": TDCavity,
  "aperture": Aperture,
  "shutter": Drift,
  "valve": Drift,
  "bellows": Drift,
  "cleaner": Monitor,

}
